server {
    listen 80;
    listen [::]:80;
    server_name imggen.djyx.me;

    root /www/wwwroot/imggen.djyx.me;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location ^~ /v1/ {
        return 308 https://$host$request_uri;
    }

    location ^~ /easyapitool-api/ {
        return 404;
    }

    location / {
        try_files $uri /index.html =404;
    }

    location ~ ^/(\.user\.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README\.md) {
        return 404;
    }

    access_log /www/wwwlogs/imggen.djyx.me.log;
    error_log /www/wwwlogs/imggen.djyx.me.error.log;
}